Disable i686 arch as it fails to build with a link error
The link error is reproduced below, let's first ship mlir and then try to solve
the issue.

/usr/bin/g++ -fPIC -O1  -fexceptions -g1 -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-copy -fno-strict-aliasing -fno-semantic-interposition -O1 -g1 -DNDEBUG  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/builddir/build/BUILD/flang-14.0.0.src/.package_note-flang-14.0.0-1.fc37.i386.ld -Wl,-z,defs -Wl,-z,nodelete   -Wl,--gc-sections -shared -Wl,-soname,libFIRBuilder.so.14 -o lib/libFIRBuilder.so.14 lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/BoxValue.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Character.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Complex.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/DoLoopHelper.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/FIRBuilder.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/MutableBox.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Assign.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Character.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Command.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Derived.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Numeric.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Ragged.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Reduction.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Stop.cpp.o lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Transformational.cpp.o  -Wl,-rpath,/builddir/build/BUILD/flang-14.0.0.src/redhat-linux-build/lib:  lib/libFIRDialect.so.14  lib/libFIRSupport.so.14  /usr/lib/libMLIRAffineAnalysis.a  /usr/lib/libMLIRAffine.a  /usr/lib/libMLIRAffineTransforms.a  /usr/lib/libMLIRAffineUtils.a  /usr/lib/libMLIRArithmetic.a  /usr/lib/libMLIRArithmeticTransforms.a  /usr/lib/libMLIRArmNeon.a  /usr/lib/libMLIRArmSVE.a  /usr/lib/libMLIRArmSVETransforms.a  /usr/lib/libMLIRAsync.a  /usr/lib/libMLIRAsyncTransforms.a  /usr/lib/libMLIRAMX.a  /usr/lib/libMLIRAMXTransforms.a  /usr/lib/libMLIRBufferization.a  /usr/lib/libMLIRBufferizationTransforms.a  /usr/lib/libMLIRComplex.a  /usr/lib/libMLIRDLTI.a  /usr/lib/libMLIREmitC.a  /usr/lib/libMLIRGPUOps.a  /usr/lib/libMLIRGPUTransforms.a  /usr/lib/libMLIRLinalgAnalysis.a  /usr/lib/libMLIRAffineBufferizableOpInterfaceImpl.a  /usr/lib/libMLIRLinalgBufferizableOpInterfaceImpl.a  /usr/lib/libMLIRModuleBufferization.a  /usr/lib/libMLIRLinalg.a  /usr/lib/libMLIRLinalgTransforms.a  /usr/lib/libMLIRLinalgUtils.a  /usr/lib/libMLIRLLVMIRTransforms.a  /usr/lib/libMLIRLLVMIR.a  /usr/lib/libMLIRNVVMIR.a  /usr/lib/libMLIRROCDLIR.a  /usr/lib/libMLIRMath.a  /usr/lib/libMLIRMathTransforms.a  /usr/lib/libMLIRMemRef.a  /usr/lib/libMLIRMemRefTransforms.a  /usr/lib/libMLIRMemRefUtils.a  /usr/lib/libMLIROpenACC.a  /usr/lib/libMLIROpenMP.a  /usr/lib/libMLIRPDL.a  /usr/lib/libMLIRPDLInterp.a  /usr/lib/libMLIRQuant.a  /usr/lib/libMLIRSCF.a  /usr/lib/libMLIRSCFTransforms.a  /usr/lib/libMLIRSCFUtils.a  /usr/lib/libMLIRShape.a  /usr/lib/libMLIRShapeOpsTransforms.a  /usr/lib/libMLIRSparseTensor.a  /usr/lib/libMLIRSparseTensorTransforms.a  /usr/lib/libMLIRSparseTensorPipelines.a  /usr/lib/libMLIRSparseTensorUtils.a  /usr/lib/libMLIRSPIRV.a  /usr/lib/libMLIRSPIRVModuleCombiner.a  /usr/lib/libMLIRSPIRVConversion.a  /usr/lib/libMLIRSPIRVTransforms.a  /usr/lib/libMLIRSPIRVUtils.a  /usr/lib/libMLIRStandard.a  /usr/lib/libMLIRStandardOpsTransforms.a  /usr/lib/libMLIRTensor.a  /usr/lib/libMLIRTensorInferTypeOpInterfaceImpl.a  /usr/lib/libMLIRTensorTilingInterfaceImpl.a  /usr/lib/libMLIRTensorTransforms.a  /usr/lib/libMLIRTensorUtils.a  /usr/lib/libMLIRTosa.a  /usr/lib/libMLIRTosaTransforms.a  /usr/lib/libMLIRVector.a  /usr/lib/libMLIRVectorTransforms.a  /usr/lib/libMLIRVectorUtils.a  /usr/lib/libMLIRX86Vector.a  /usr/lib/libMLIRX86VectorTransforms.a  /usr/lib/libMLIRAsync.a  /usr/lib/libMLIRGPUOps.a  /usr/lib/libMLIRDLTI.a  /usr/lib/libMLIRLLVMToLLVMIRTranslation.a  /usr/lib/libMLIRShape.a  /usr/lib/libMLIRSparseTensorTransforms.a  /usr/lib/libMLIRLinalgTransforms.a  /usr/lib/libMLIRLinalgAnalysis.a  /usr/lib/libMLIRAffineBufferizableOpInterfaceImpl.a  /usr/lib/libMLIRLinalgBufferizableOpInterfaceImpl.a  /usr/lib/libMLIRModuleBufferization.a  /usr/lib/libMLIRLinalgUtils.a  /usr/lib/libMLIRTensorUtils.a  /usr/lib/libMLIRStandardToLLVM.a  /usr/lib/libMLIRArithmeticToLLVM.a  /usr/lib/libMLIRVectorToSCF.a  /usr/lib/libMLIRSCFTransforms.a  /usr/lib/libMLIRSCFUtils.a  /usr/lib/libMLIRSparseTensor.a  /usr/lib/libMLIRSparseTensorUtils.a  /usr/lib/libMLIRStandardOpsTransforms.a  /usr/lib/libMLIRArithmeticTransforms.a  /usr/lib/libMLIRTensorTransforms.a  /usr/lib/libMLIRBufferizationTransforms.a  /usr/lib/libMLIRVectorToLLVM.a  /usr/lib/libMLIRArmNeon.a  /usr/lib/libMLIRArmSVETransforms.a  /usr/lib/libMLIRArmSVE.a  /usr/lib/libMLIRAMXTransforms.a  /usr/lib/libMLIRAMX.a  /usr/lib/libMLIRVectorTransforms.a  /usr/lib/libMLIRVectorUtils.a  /usr/lib/libMLIRX86VectorTransforms.a  /usr/lib/libMLIRX86Vector.a  /usr/lib/libMLIRTargetLLVMIRExport.a  /usr/lib/libMLIRLLVMIRTransforms.a  /usr/lib/libMLIRTranslation.a  /usr/lib/libMLIRSCFToStandard.a  /usr/lib/libMLIRAffineToStandard.a  /usr/lib/libMLIRVector.a  /usr/lib/libMLIRAffineUtils.a  /usr/lib/libMLIRAffineAnalysis.a  /usr/lib/libMLIRPresburger.a  /usr/lib/libMLIRMathToLLVM.a  /usr/lib/libMLIRMemRefToLLVM.a  /usr/lib/libMLIRLLVMCommonConversion.a  /usr/lib/libMLIRLLVMIR.a  /usr/lib/libMLIRReconcileUnrealizedCasts.a  /usr/lib/libMLIRSPIRVConversion.a  /usr/lib/libMLIRSPIRV.a  /usr/lib/libMLIRTransforms.a  /usr/lib/libMLIRCopyOpInterface.a  /usr/lib/libMLIRLinalg.a  /usr/lib/libMLIRAffine.a  /usr/lib/libMLIRMath.a  /usr/lib/libMLIRParser.a  /usr/lib/libMLIRSCF.a  /usr/lib/libMLIRBufferization.a  /usr/lib/libMLIRMemRef.a  /usr/lib/libMLIRMemRefUtils.a  /usr/lib/libMLIRLoopLikeInterface.a  /usr/lib/libMLIRTilingInterface.a  /usr/lib/libMLIRTosa.a  /usr/lib/libMLIRQuant.a  /usr/lib/libMLIRTransformUtils.a  /usr/lib/libMLIRRewrite.a  /usr/lib/libMLIRPDLToPDLInterp.a  /usr/lib/libMLIRPDLInterp.a  /usr/lib/libMLIRPDL.a  /usr/lib/libMLIRTensor.a  /usr/lib/libMLIRComplex.a  /usr/lib/libMLIRStandard.a  /usr/lib/libMLIRArithmetic.a  /usr/lib/libMLIRVectorInterfaces.a  /usr/lib/libMLIRDialectUtils.a  /usr/lib/libMLIRCastInterfaces.a  /usr/lib/libMLIRDialect.a  /usr/lib/libMLIRPass.a  /usr/lib/libMLIRAnalysis.a  /usr/lib/libMLIRCallInterfaces.a  /usr/lib/libMLIRControlFlowInterfaces.a  /usr/lib/libMLIRInferTypeOpInterface.a  /usr/lib/libMLIRSideEffectInterfaces.a  /usr/lib/libMLIRDataLayoutInterfaces.a  /usr/lib/libMLIRViewLikeInterface.a  /usr/lib/libMLIRIR.a  /usr/lib/libMLIRSupport.a  /usr/lib/libLLVM-14.so && :
/usr/bin/ld: lib/Optimizer/Builder/CMakeFiles/obj.FIRBuilder.dir/Runtime/Character.cpp.o: in function `fir::runtime::RuntimeTableKey<int (char const*, char const*, unsigned int, unsigned int)>::getTypeModel()::{lambda(mlir::MLIRContext*)#1}::operator()(mlir::MLIRContext*) const':
/builddir/build/BUILD/flang-14.0.0.src/include/flang/Optimizer/Builder/Runtime/RTBuilder.h:296: undefined reference to `mlir::Type (*fir::runtime::getModel<unsigned int>())(mlir::MLIRContext*)'
/usr/bin/ld: /builddir/build/BUILD/flang-14.0.0.src/include/flang/Optimizer/Builder/Runtime/RTBuilder.h:296: undefined reference to `mlir::Type (*fir::runtime::getModel<unsigned int>())(mlir::MLIRContext*)'
[...]